export function drawChart(canvas,series,visibleThroughIndex,cutoffIndex){
 const dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(); canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const W=rect.width,H=rect.height,p={l:58,r:26,t:26,b:42};ctx.clearRect(0,0,W,H);ctx.fillStyle='#070707';ctx.fillRect(0,0,W,H);
 const all=series.flatMap(s=>s.values.slice(0,visibleThroughIndex+1).filter(v=>Number.isFinite(v.value)));if(!all.length)return;let min=Math.min(...all.map(v=>v.value)),max=Math.max(...all.map(v=>v.value));const pad=(max-min||1)*.18;min-=pad;max+=pad;ctx.font='10px -apple-system,system-ui';ctx.fillStyle='#666661';ctx.strokeStyle='#1d1d1d';ctx.lineWidth=1;
 for(let i=0;i<5;i++){const yy=p.t+(H-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(W-p.r,yy);ctx.stroke();ctx.fillText((max-(max-min)*i/4).toFixed(2)+'%',8,yy+3)}
 const count=Math.max(...series.map(s=>s.values.length)),x=i=>p.l+(W-p.l-p.r)*(count<=1?0:i/(count-1)),y=v=>p.t+(H-p.t-p.b)*(max-v)/(max-min);
 series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.beginPath();let started=false;s.values.slice(0,visibleThroughIndex+1).forEach((d,i)=>{if(!Number.isFinite(d.value))return;const xx=x(i),yy=y(d.value);started?ctx.lineTo(xx,yy):(ctx.moveTo(xx,yy),started=true)});ctx.stroke()});
 const labels=series[0]?.values||[],last=Math.min(visibleThroughIndex,labels.length-1);ctx.fillStyle='#6d6d68';[0,Math.floor(last/2),last].filter((v,i,a)=>a.indexOf(v)===i).forEach(i=>{if(labels[i])ctx.fillText(labels[i].date.slice(5),x(i)-16,H-15)});
 const cx=x(Math.min(cutoffIndex,count-1));ctx.setLineDash([4,5]);ctx.strokeStyle='#9b8355';ctx.beginPath();ctx.moveTo(cx,p.t);ctx.lineTo(cx,H-p.b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#b49a65';ctx.font='9px -apple-system,system-ui';ctx.fillText('CUTOFF',Math.min(cx+7,W-68),p.t+10);
 if(visibleThroughIndex>cutoffIndex){const vx=x(Math.min(visibleThroughIndex,count-1));ctx.strokeStyle='#55534d';ctx.beginPath();ctx.moveTo(vx,p.t);ctx.lineTo(vx,H-p.b);ctx.stroke();ctx.fillStyle='#77736b';ctx.fillText('VIEW',Math.min(vx+7,W-55),p.t+10)}
}
